openapi: 3.0.1
info:
  title: monster-satyr
  x-cortex-tag: monster-satyr
  x-cortex-custom-metadata:
    alignment: neutral-good
    type: fiend
    challenge_rating: 28
    legendary: true
    armor_class: 14
    hit_points: 172
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-satyr
      alias: github-token-test
